### ISSUE TITLE
Audio segment

### ISSUE THREAD

**Issue by Swagger-z** [huangruizhe/ConEC#1]
Hello~
I am currently working on integrating the 'earnings21' dataset into my ASR model, which does not support long-form audio inputs. and i noticed that there are .nlp files with ts and endts annotations under the timestamps dir. Should I proceed with manually segmenting the audio using these timestamps or  if there are pre-segmented audio files available?

Best regards

**Comment by huangruizhe** [comment]
Yes, you could use the timestamps to segment the audio, e.g., by sentences. Those timestamps are automatically tagged and refined.

**Comment by Swagger-z** [comment]
I do try to segment audio by sentences, using punctuation marks (., ?, !) as indicators of sentence ends, and the following token as the start of the next sentence . The issue I'm encountering is that sometimes these punctuation-marked tokens do not have corresponding timestamps. Could you suggest any good approaches to handle this?

**Comment by huangruizhe** [comment]
Oh, thanks for mentioning the issue! Just checked the codes I was using at that time -- yeah there's a mechanism to handle the situation you mentioned (-- i almost forget that), although it is kinda complicated imo..

1. Different alignment tools were used to get the timestamps -- then only the timestamps that's agreed by all tools are kept.
2. The segments are divided by punctuations and speaker information.
3. For each segment, the boundary time is decided by the beginning and ending words -- if they don't have timestamps, look for the timestamps from the neighboring words such that the segment is "contained".
4. Do ASR on each segment. Shift the segments' beginning/ending timestamps if there's insertion or deletion error at the beginning/ending of the segment.

There should be a better way to handle this.
I am attaching the segments that I used. You could use [lhotse](https://github.com/lhotse-speech/lhotse) to parse it or simply parse it as a jsonl file and extract the segments. 
[ec21_cuts.iter6.wer.updated.jsonl.gz](https://github.com/user-attachments/files/16517958/ec21_cuts.iter6.wer.updated.jsonl.gz)

**Comment by Swagger-z** [comment]
thanks~ it‘s much more complicated than I think, the segments help a lot！
